/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 boy.glb 
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Boy(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/resources/boy.glb')
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    
    const action = props.action.currentAction;
    mixer.stopAllAction();

    if (action === 'forward' || action ==='backward' || action ==='leftward'|| action==='rightward' || action==='run') {
      actions.walking.reset().play();
    } 
    else {
      actions.idle.reset().play();
    }
  }, [props.action.currentAction, actions, mixer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="BOY" geometry={nodes.BOY.geometry} material={materials.Boy} skeleton={nodes.BOY.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default Boy;
useGLTF.preload('/resources/boy.glb')
