/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 chandelier.glb 
Author: ankakuz (https://sketchfab.com/ankaku10)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chandelier-a608b8c0310a417cafded2a238cd91f5
Title: Chandelier
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chandelier(props) {
  const { nodes, materials } = useGLTF('/resources/chandelier.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 95.91]}>
          <mesh geometry={nodes.Object_319.geometry} material={materials.material} position={[0, 0, -95.91]} />
        </group>
        <group position={[2.529, 0, 500.611]} rotation={[1.529, 0.965, -1.535]}>
          <mesh geometry={nodes.Object_322.geometry} material={materials.material} position={[500.418, -2.46, -13.9]} rotation={[-0.086, -1.547, 0.52]} />
        </group>
        <group position={[-2.977, -4.454, 534.885]} rotation={[-1.419, 1.021, 1.393]}>
          <mesh geometry={nodes.Object_325.geometry} material={materials.material} position={[532.885, 27.717, -37.363]} rotation={[0.542, -1.479, 0]} />
        </group>
        <group position={[-6.141, -4.454, 569.085]} rotation={[1.583, 1.28, -1.561]}>
          <mesh geometry={nodes.Object_328.geometry} material={materials.material} position={[569.062, -6.252, 6.655]} rotation={[-1.736, -1.549, -1.445]} />
        </group>
        <group position={[-6.338, -6.015, 641.002]} rotation={[1.583, 1.277, -1.561]}>
          <mesh geometry={nodes.Object_331.geometry} material={materials.material} position={[640.996, -6.232, 6.674]} rotation={[-1.739, -1.549, -1.445]} />
        </group>
        <group position={[-9.195, -0.646, 673.655]} rotation={[-1.627, 0.811, 1.573]}>
          <mesh geometry={nodes.Object_334.geometry} material={materials.material} position={[672.613, 19.777, 33.108]} rotation={[2.363, -1.517, 1.604]} />
        </group>
        <group position={[-7.932, -4.767, 606.132]} rotation={[-1.677, 0.674, 1.62]}>
          <mesh geometry={nodes.Object_337.geometry} material={materials.material} position={[603.289, 7.028, 58.941]} rotation={[2.941, -1.486, 2.046]} />
        </group>
        <group rotation={[0, 0, -Math.PI / 4]}>
          <group position={[203.109, 4.737, 264.819]}>
            <mesh geometry={nodes.Object_31.geometry} material={materials.material_1} position={[-203.109, -4.737, -264.819]} rotation={[0, 0, Math.PI / 4]} />
          </group>
          <group position={[203.109, 4.737, 320.405]}>
            <mesh geometry={nodes.Object_34.geometry} material={materials.material_2} position={[-203.109, -4.737, -320.405]} rotation={[0, 0, Math.PI / 4]} />
          </group>
          <group position={[203.109, 4.737, 218.689]}>
            <mesh geometry={nodes.Object_37.geometry} material={materials.material} position={[-203.109, -4.737, -218.689]} rotation={[0, 0, Math.PI / 4]} />
          </group>
          <group position={[203.498, -1.169, 234.992]} rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.Object_40.geometry} material={materials.material} position={[203.498, 1.169, 234.992]} rotation={[Math.PI, 0, -2.356]} />
          </group>
          <mesh geometry={nodes.Object_45.geometry} material={materials.material} rotation={[0, 0, Math.PI / 4]} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.material} rotation={[0, 0, Math.PI / 4]} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.material} rotation={[0, 0, Math.PI / 4]} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.material} rotation={[0, 0, Math.PI / 4]} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.material} rotation={[0, 0, Math.PI / 4]} />
          <mesh geometry={nodes.Object_60.geometry} material={materials.material} rotation={[0, 0, Math.PI / 4]} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.material} rotation={[0, 0, Math.PI / 4]} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.material} rotation={[0, 0, Math.PI / 4]} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.material} rotation={[0, 0, Math.PI / 4]} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.material} rotation={[0, 0, Math.PI / 4]} />
        </group>
        <group rotation={[0, 0, -Math.PI / 2]}>
          <group position={[203.109, 4.737, 264.819]}>
            <mesh geometry={nodes.Object_74.geometry} material={materials.material_1} position={[-203.109, -4.737, -264.819]} rotation={[0, 0, Math.PI / 2]} />
          </group>
          <group position={[203.109, 4.737, 320.405]}>
            <mesh geometry={nodes.Object_77.geometry} material={materials.material_2} position={[-203.109, -4.737, -320.405]} rotation={[0, 0, Math.PI / 2]} />
          </group>
          <group position={[203.109, 4.737, 218.689]}>
            <mesh geometry={nodes.Object_80.geometry} material={materials.material} position={[-203.109, -4.737, -218.689]} rotation={[0, 0, Math.PI / 2]} />
          </group>
          <group position={[203.498, -1.169, 234.992]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_83.geometry} material={materials.material} position={[203.498, 1.169, 234.992]} rotation={[Math.PI, 0, -Math.PI / 2]} />
          </group>
          <mesh geometry={nodes.Object_87.geometry} material={materials.material} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_89.geometry} material={materials.material} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_92.geometry} material={materials.material} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_94.geometry} material={materials.material} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.material} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.material} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_102.geometry} material={materials.material} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_105.geometry} material={materials.material} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_107.geometry} material={materials.material} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.material} rotation={[0, 0, Math.PI / 2]} />
        </group>
        <group rotation={[0, 0, -2.356]}>
          <group position={[203.109, 4.737, 264.819]}>
            <mesh geometry={nodes.Object_113.geometry} material={materials.material_1} position={[-203.109, -4.737, -264.819]} rotation={[0, 0, 2.356]} />
          </group>
          <group position={[203.109, 4.737, 320.405]}>
            <mesh geometry={nodes.Object_116.geometry} material={materials.material_2} position={[-203.109, -4.737, -320.405]} rotation={[0, 0, 2.356]} />
          </group>
          <group position={[203.109, 4.737, 218.689]}>
            <mesh geometry={nodes.Object_119.geometry} material={materials.material} position={[-203.109, -4.737, -218.689]} rotation={[0, 0, 2.356]} />
          </group>
          <group position={[203.498, -1.169, 234.992]} rotation={[-Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.Object_122.geometry} material={materials.material} position={[203.498, 1.169, 234.992]} rotation={[-Math.PI, 0, -Math.PI / 4]} />
          </group>
          <mesh geometry={nodes.Object_127.geometry} material={materials.material} rotation={[0, 0, 2.356]} />
          <mesh geometry={nodes.Object_129.geometry} material={materials.material} rotation={[0, 0, 2.356]} />
          <mesh geometry={nodes.Object_133.geometry} material={materials.material} rotation={[0, 0, 2.356]} />
          <mesh geometry={nodes.Object_135.geometry} material={materials.material} rotation={[0, 0, 2.356]} />
          <mesh geometry={nodes.Object_137.geometry} material={materials.material} rotation={[0, 0, 2.356]} />
          <mesh geometry={nodes.Object_142.geometry} material={materials.material} rotation={[0, 0, 2.356]} />
          <mesh geometry={nodes.Object_144.geometry} material={materials.material} rotation={[0, 0, 2.356]} />
          <mesh geometry={nodes.Object_148.geometry} material={materials.material} rotation={[0, 0, 2.356]} />
          <mesh geometry={nodes.Object_150.geometry} material={materials.material} rotation={[0, 0, 2.356]} />
          <mesh geometry={nodes.Object_152.geometry} material={materials.material} rotation={[0, 0, 2.356]} />
        </group>
        <group rotation={[0, 0, -Math.PI]}>
          <group position={[203.109, 4.737, 264.819]}>
            <mesh geometry={nodes.Object_156.geometry} material={materials.material_1} position={[-203.109, -4.737, -264.819]} rotation={[0, 0, Math.PI]} />
          </group>
          <group position={[203.109, 4.737, 320.405]}>
            <mesh geometry={nodes.Object_159.geometry} material={materials.material_2} position={[-203.109, -4.737, -320.405]} rotation={[0, 0, Math.PI]} />
          </group>
          <group position={[203.109, 4.737, 218.689]}>
            <mesh geometry={nodes.Object_162.geometry} material={materials.material} position={[-203.109, -4.737, -218.689]} rotation={[0, 0, Math.PI]} />
          </group>
          <group position={[203.498, -1.169, 234.992]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_165.geometry} material={materials.material} position={[203.498, 1.169, 234.992]} rotation={[Math.PI, 0, 0]} />
          </group>
          <mesh geometry={nodes.Object_169.geometry} material={materials.material} rotation={[0, 0, Math.PI]} />
          <mesh geometry={nodes.Object_171.geometry} material={materials.material} rotation={[0, 0, Math.PI]} />
          <mesh geometry={nodes.Object_174.geometry} material={materials.material} rotation={[0, 0, Math.PI]} />
          <mesh geometry={nodes.Object_176.geometry} material={materials.material} rotation={[0, 0, Math.PI]} />
          <mesh geometry={nodes.Object_178.geometry} material={materials.material} rotation={[0, 0, Math.PI]} />
          <mesh geometry={nodes.Object_182.geometry} material={materials.material} rotation={[0, 0, Math.PI]} />
          <mesh geometry={nodes.Object_184.geometry} material={materials.material} rotation={[0, 0, Math.PI]} />
          <mesh geometry={nodes.Object_187.geometry} material={materials.material} rotation={[0, 0, Math.PI]} />
          <mesh geometry={nodes.Object_189.geometry} material={materials.material} rotation={[0, 0, Math.PI]} />
          <mesh geometry={nodes.Object_191.geometry} material={materials.material} rotation={[0, 0, Math.PI]} />
        </group>
        <group rotation={[0, 0, 2.356]}>
          <group position={[203.109, 4.737, 264.819]}>
            <mesh geometry={nodes.Object_195.geometry} material={materials.material_1} position={[-203.109, -4.737, -264.819]} rotation={[0, 0, -2.356]} />
          </group>
          <group position={[203.109, 4.737, 320.405]}>
            <mesh geometry={nodes.Object_198.geometry} material={materials.material_2} position={[-203.109, -4.737, -320.405]} rotation={[0, 0, -2.356]} />
          </group>
          <group position={[203.109, 4.737, 218.689]}>
            <mesh geometry={nodes.Object_201.geometry} material={materials.material} position={[-203.109, -4.737, -218.689]} rotation={[0, 0, -2.356]} />
          </group>
          <group position={[203.498, -1.169, 234.992]} rotation={[Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_204.geometry} material={materials.material} position={[203.498, 1.169, 234.992]} rotation={[Math.PI, 0, Math.PI / 4]} />
          </group>
          <mesh geometry={nodes.Object_209.geometry} material={materials.material} rotation={[0, 0, -2.356]} />
          <mesh geometry={nodes.Object_211.geometry} material={materials.material} rotation={[0, 0, -2.356]} />
          <mesh geometry={nodes.Object_215.geometry} material={materials.material} rotation={[0, 0, -2.356]} />
          <mesh geometry={nodes.Object_217.geometry} material={materials.material} rotation={[0, 0, -2.356]} />
          <mesh geometry={nodes.Object_219.geometry} material={materials.material} rotation={[0, 0, -2.356]} />
          <mesh geometry={nodes.Object_224.geometry} material={materials.material} rotation={[0, 0, -2.356]} />
          <mesh geometry={nodes.Object_226.geometry} material={materials.material} rotation={[0, 0, -2.356]} />
          <mesh geometry={nodes.Object_230.geometry} material={materials.material} rotation={[0, 0, -2.356]} />
          <mesh geometry={nodes.Object_232.geometry} material={materials.material} rotation={[0, 0, -2.356]} />
          <mesh geometry={nodes.Object_234.geometry} material={materials.material} rotation={[0, 0, -2.356]} />
        </group>
        <group rotation={[0, 0, Math.PI / 2]}>
          <group position={[203.109, 4.737, 264.819]}>
            <mesh geometry={nodes.Object_238.geometry} material={materials.material_1} position={[-203.109, -4.737, -264.819]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <group position={[203.109, 4.737, 320.405]}>
            <mesh geometry={nodes.Object_241.geometry} material={materials.material_2} position={[-203.109, -4.737, -320.405]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <group position={[203.109, 4.737, 218.689]}>
            <mesh geometry={nodes.Object_244.geometry} material={materials.material} position={[-203.109, -4.737, -218.689]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <group position={[203.498, -1.169, 234.992]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_247.geometry} material={materials.material} position={[203.498, 1.169, 234.992]} rotation={[-Math.PI, 0, Math.PI / 2]} />
          </group>
          <mesh geometry={nodes.Object_251.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_253.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_256.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_258.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_260.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_264.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_266.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_269.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_271.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_273.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 2]} />
        </group>
        <group rotation={[0, 0, Math.PI / 4]}>
          <group position={[203.109, 4.737, 264.819]}>
            <mesh geometry={nodes.Object_277.geometry} material={materials.material_1} position={[-203.109, -4.737, -264.819]} rotation={[0, 0, -Math.PI / 4]} />
          </group>
          <group position={[203.109, 4.737, 320.405]}>
            <mesh geometry={nodes.Object_280.geometry} material={materials.material_2} position={[-203.109, -4.737, -320.405]} rotation={[0, 0, -Math.PI / 4]} />
          </group>
          <group position={[203.109, 4.737, 218.689]}>
            <mesh geometry={nodes.Object_283.geometry} material={materials.material} position={[-203.109, -4.737, -218.689]} rotation={[0, 0, -Math.PI / 4]} />
          </group>
          <group position={[203.498, -1.169, 234.992]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_286.geometry} material={materials.material} position={[203.498, 1.169, 234.992]} rotation={[-Math.PI, 0, 2.356]} />
          </group>
          <mesh geometry={nodes.Object_291.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_293.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_297.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_299.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_301.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_306.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_308.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_312.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_314.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_316.geometry} material={materials.material} rotation={[0, 0, -Math.PI / 4]} />
        </group>
        <group position={[203.109, 4.737, 264.819]}>
          <mesh geometry={nodes.Object_6.geometry} material={materials.material_1} position={[-203.109, -4.737, -264.819]} />
        </group>
        <group position={[203.109, 4.737, 320.405]}>
          <mesh geometry={nodes.Object_9.geometry} material={materials.material_2} position={[-203.109, -4.737, -320.405]} />
        </group>
        <group position={[203.109, 4.737, 218.689]}>
          <mesh geometry={nodes.Object_12.geometry} material={materials.material} position={[-203.109, -4.737, -218.689]} />
        </group>
        <group position={[203.498, -1.169, 234.992]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Object_15.geometry} material={materials.material} position={[203.498, 1.169, 234.992]} rotation={[-Math.PI, 0, -Math.PI]} />
        </group>
        <mesh geometry={nodes.Object_21.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.material} />
      </group>
    </group>
  )
}
export default Chandelier
useGLTF.preload('/resources/chandelier.glb')
