/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gentleman.glb 
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Gentleman(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/resources/gentleman.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    
    actions.idle.play();

  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="back" geometry={nodes.back.geometry} material={materials['Material.009']} skeleton={nodes.back.skeleton} />
          <skinnedMesh name="body" geometry={nodes.body.geometry} material={materials['Material.015']} skeleton={nodes.body.skeleton} />
          <skinnedMesh name="body001" geometry={nodes.body001.geometry} material={materials['Material.014']} skeleton={nodes.body001.skeleton} />
          <skinnedMesh name="body002" geometry={nodes.body002.geometry} material={materials['Material.014']} skeleton={nodes.body002.skeleton} />
          <skinnedMesh name="coat" geometry={nodes.coat.geometry} material={materials['Material.009']} skeleton={nodes.coat.skeleton} />
          <skinnedMesh name="groin" geometry={nodes.groin.geometry} material={materials['Material.002']} skeleton={nodes.groin.skeleton} />
          <skinnedMesh name="left" geometry={nodes.left.geometry} material={materials['Material.017']} skeleton={nodes.left.skeleton} />
          <skinnedMesh name="left_center" geometry={nodes.left_center.geometry} material={materials['Material.001']} skeleton={nodes.left_center.skeleton} />
          <skinnedMesh name="left_leg" geometry={nodes.left_leg.geometry} material={materials['Material.002']} skeleton={nodes.left_leg.skeleton} />
          <skinnedMesh name="right" geometry={nodes.right.geometry} material={materials['Material.017']} skeleton={nodes.right.skeleton} />
          <skinnedMesh name="right_center" geometry={nodes.right_center.geometry} material={materials['Material.001']} skeleton={nodes.right_center.skeleton} />
          <skinnedMesh name="shirt" geometry={nodes.shirt.geometry} material={materials['Material.013']} skeleton={nodes.shirt.skeleton} />
          <skinnedMesh name="shoe_left" geometry={nodes.shoe_left.geometry} material={materials['Material.003']} skeleton={nodes.shoe_left.skeleton} />
          <skinnedMesh name="Torus" geometry={nodes.Torus.geometry} material={materials['Material.001']} skeleton={nodes.Torus.skeleton} />
          <skinnedMesh name="실린더" geometry={nodes.실린더.geometry} material={materials['Material.009']} skeleton={nodes.실린더.skeleton} />
        </group>
      </group>
    </group>
  )
}
export default Gentleman;

useGLTF.preload('/gentleman.glb')
