/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 vault_door.glb 
Author: ShakibSKb (https://sketchfab.com/shakibskb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vault-door-2de2322bf07d496bbcc19d94400a469f
Title: Vault Door
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Vault_door(props) {
  const { nodes, materials } = useGLTF('/resources/vault_door.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder2_Black_Metal_0.geometry} material={materials.Black_Metal} />
      <mesh geometry={nodes.pCylinder3_Black_Metal_0.geometry} material={materials.Black_Metal} />
      <mesh geometry={nodes.pCylinder4_Black_Metal_0.geometry} material={materials.Black_Metal} />
      <mesh geometry={nodes.pCylinder5_Black_Metal_0.geometry} material={materials.Black_Metal} />
      <mesh geometry={nodes.pCylinder6_Black_Metal_0.geometry} material={materials.Black_Metal} />
      <mesh geometry={nodes.Steel_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Steel1_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Steel2_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Steel3_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Steel4_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Steel5_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Steel6_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Steel7_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Finger_Finger2_0.geometry} material={materials.Finger2} position={[0, 0, 1.141]} scale={[1.125, 1.439, 0.239]} />
      <mesh geometry={nodes.pCylinder29_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.pCylinder27_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Nut_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Nut1_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.Nut2_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.pCylinder8_Black_Metal_0.geometry} material={materials.Black_Metal} />
      <mesh geometry={nodes.Cebar_Black_Metal_0.geometry} material={materials.Black_Metal} />
      <group position={[0, 0, 0.684]}>
        <mesh geometry={nodes.Pin_Side_Black_Metal_0.geometry} material={materials.Black_Metal} />
        <mesh geometry={nodes.pCube1_Black_Metal_0.geometry} material={materials.Black_Metal} />
        <mesh geometry={nodes.pCube2_Black_Metal_0.geometry} material={materials.Black_Metal} />
        <mesh geometry={nodes.Up_Cd2_Steel8_0.geometry} material={materials.Steel8} position={[0, 0, -0.017]} />
        <mesh geometry={nodes.Up_Cd1_Steel8_0.geometry} material={materials.Steel8} position={[0, 0, -0.017]} />
        <mesh geometry={nodes.Up_Cd_Steel8_0.geometry} material={materials.Steel8} position={[0, 0, -0.017]} />
        <mesh geometry={nodes.Nut3_Steel8_0.geometry} material={materials.Steel8} position={[0, 0, -0.089]} />
        <mesh geometry={nodes.Machin_blinn3_0.geometry} material={materials.blinn3} position={[0.376, 0.113, 0.205]} />
      </group>
      <group position={[0, 0, -0.046]}>
        <mesh geometry={nodes.pCylinder11_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder12_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder13_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder14_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder15_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder16_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder17_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder18_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder19_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder20_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder21_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder22_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder23_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder24_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder25_Steel8_0.geometry} material={materials.Steel8} />
        <mesh geometry={nodes.pCylinder26_Steel8_0.geometry} material={materials.Steel8} />
      </group>
      <mesh geometry={nodes.pCylinder10_Black_Metal_0.geometry} material={materials.Black_Metal} />
      <mesh geometry={nodes.Ball_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.pCylinder9_Black_Metal_0.geometry} material={materials.Black_Metal} />
      <mesh geometry={nodes.Ball1_Steel8_0.geometry} material={materials.Steel8} />
      <mesh geometry={nodes.pCylinder7_Black_Metal_0.geometry} material={materials.Black_Metal} />
    </group>
  )
}
export default Vault_door
useGLTF.preload('/resources/vault_door.glb')
